# Generated by Django 2.1.7 on 2019-02-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190224_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short',
            field=models.CharField(max_length=64),
        ),
    ]
